<a href="https://colab.research.google.com/github/cweikucf/cap4630/blob/master/HW_1/ConnerWeik_CAP4630_Homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Conner Weik, CAP 4630, Spring 2020**
# **Homework 1**


This code takes a list of numpy arrays and multiplies them sequentially, from first to last. A custom error will be raised if the list is empty or if two matrices are found to be incompatible.

# Definition of compatibility of matrices for matrix multiplication

Let $A \in \Bbb R^{m\ x\ n}$ and $B \in \Bbb R^{o\ x\ p}$ be matrices, $m,\ n,\ o,\ p \in \Bbb N^+$.

The matrix product $AB$ is defined if and only if the inner dimensions of $A$ and $B$ are the same, that is, if $n = o$.

# Function and custom exception class code

In [0]:
# Function that takes an array of numpy matrices, list, and performs matrix mulitplication sequentially until it completes or there is an error.
def multiplyMatrixList(list):
  if len(list) == 0:
    raise MatrixMultError("Error: The list of matrices is empty.")
  while len(list) > 1:
    try:
      matrixA = list[0]
      matrixB = list[1]
      del list[0]
      del list[0]
      list.insert(0, numpy.matmul(matrixA, matrixB))
    except:
      raise MatrixMultError("Error: Matrix with dimensions " + str(len(matrixA)) + "x" + str(len(matrixA[0])) + " cannot be multiplied with matrix with dimenions " + str(len(matrixB)) + "x" + str(len(matrixB[0])))
  
  return list[0]

# Custom exception class.
class MatrixMultError(Exception):
  def print_tb():
    super().print_tb()

# Demonstration

In [0]:
# Demo 1
def demo1():
  matrix1 = numpy.array([
      [1, 2, 3],

      [4, 5, 6],
      [7, 8, 9]
  ])

  matrix2 = numpy.array([
                         [10],
                         [10],
                         [10]
  ])

  matrix3 = numpy.array([
                         [2, 3, 4, 5]
  ])

  matrixList = [matrix1, matrix2, matrix3]
  return multiplyMatrixList(matrixList)

# Demo 2
def demo2():
  matrixList = [ numpy.array([
                              [2, 2],
                              [2, 2]
  ]),
                 numpy.array([
                              [2, 2],
                              [2, 2]
  ]),
                 numpy.array([
                              [2, 2],
                              [2, 2]
  ]),
                 numpy.array([
                              [2, 2],
                              [2, 2]
  ])]

  return multiplyMatrixList(matrixList)

# Empty List Demo

def emptyListDemo():
  matrixList = []
  return multiplyMatrixList(matrixList)


  

print("Demo 1:")
print(demo1())
print ("Demo 2:")
print(demo2())

Demo 1:
[[ 120  180  240  300]
 [ 300  450  600  750]
 [ 480  720  960 1200]]
Demo 2:
[[128 128]
 [128 128]]


# Empty List Demonstration

In [0]:
def empyListDemo():
  matrixList = []
  return multiplyMatrixList(MatrixList)

print("Empty list:")
print(emptyListDemo())

Empty List:


MatrixMultError: ignored

# Incompatible Matrices Demonstration

In [0]:
def incompatibleMatricesDemo():
  matrix1 = numpy.array([
                         [1, 2, 3],
                         [4, 5, 6]
  ])

  matrix2 = numpy.array([
                         [1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [5129, 327, 2332, 123]
  ])
  
  matrix3 = numpy.array([
                         [1]
  ])

  matrixList = [matrix1, matrix2, matrix3]
  return multiplyMatrixList(matrixList)

print("Incompatible matrices:")
print(incompatibleMatricesDemo())

Incompatible matrices:


MatrixMultError: ignored